# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "opencensus", "~> 0.4.0"

gem "sinatra", "~> 2.0"

gem "google-cloud-vision", "~> 0.32.2"

gem "opencensus-stackdriver", "~> 0.2.0"
